services:
  db:
    image: postgres:16-alpine
    container_name: simple-social-db-orch-local
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}_LOCAL
      POSTGRES_USER: ${DB_USER}_LOCAL
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - social_db_data_local:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: simple-social-backend
    container_name: simple-social-backend-orch-local
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: simple-social-frontend
    container_name: simple-social-frontend-orch
    restart: always
    depends_on:
      - backend
    ports:
      - "5500:80"

volumes:
  social_db_data_local:
