services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: simple-social-backend
    container_name: simple-social-backend-local
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - backend_local_data:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: simple-social-frontend
    container_name: simple-social-frontend-local
    restart: always
    depends_on:
      - backend
    ports:
      - "5500:80"

volumes:
  backend_local_data:
