services:
  backend:
    image: ghcr.io/ai25m016/simple-social-backend:latest
    container_name: simple-social-backend
    ports:
      - "8000:8000"

  frontend:
    image: ghcr.io/ai25m016/simple-social-frontend:latest
    container_name: simple-social-frontend
    ports:
      - "5500:80"
    depends_on:
      - backend
